#!/usr/bin/env bash
# Copyright (c) 2026 The BTX developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

export LC_ALL=C
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
out="$repo_root/doc/btx-matmul-v4.7-documentation-inventory.md"
tmp="$(mktemp "${TMPDIR:-/tmp}/btx-v47-doc-inventory.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

mapfile_cmd=()
if command -v rg >/dev/null 2>&1; then
    mapfile_cmd=(
        rg --files
        -g '*.md' -g '*.markdown' -g '*.rst' -g '*.txt'
        -g '!build-*' -g '!depends/work/**'
        -g '!src/leveldb/**' -g '!src/secp256k1/**'
    )
else
    echo "error: rg is required" >&2
    exit 1
fi

files="$("${mapfile_cmd[@]}" | sort)"
total="$(printf '%s\n' "$files" | sed '/^$/d' | wc -l | tr -d ' ')"
matmul=0
reviewed=0
required=0

rows="$(mktemp "${TMPDIR:-/tmp}/btx-v47-doc-rows.XXXXXX")"
trap 'rm -f "$tmp" "$rows"' EXIT

while IFS= read -r rel; do
    [[ -n "$rel" ]] || continue
    file="$repo_root/$rel"
    disposition="General documentation; no MatMul transition claim found"
    if rg -qi \
        'matmul|exactreplay|exact replay|enc_rc|resident curriculum|succinct proof|nMatMulRCProfile' \
        "$file"; then
        matmul=$((matmul + 1))
        if [[ "$rel" == "doc/btx-matmul-v4.7-transition-roadmap.md" ]]; then
            disposition="Canonical v4.7 transition roadmap"
            reviewed=$((reviewed + 1))
        elif [[ "$rel" == "doc/release-notes.md" ||
                "$rel" == "doc/release-notes/release-notes-0.33.2.md" ]]; then
            disposition="Release-candidate note; activation-disabled implementation release"
            reviewed=$((reviewed + 1))
        elif rg -q 'btx-matmul-v4\.7-transition-roadmap' "$file"; then
            disposition="MatMul-related; reviewed against canonical roadmap"
            reviewed=$((reviewed + 1))
        elif [[ "$rel" == doc/release-notes/* ]]; then
            disposition="Reviewed immutable release record; historical behavior preserved"
            reviewed=$((reviewed + 1))
        else
            case "$rel" in
                doc/btx-deep-code-analysis-2026-03-07.md|\
                doc/btx-evx-finality-coupling.md|\
                doc/btx-implementation-analysis.md|\
                doc/btx-live-runtime-validation-2026-03-07.md|\
                doc/btx-p2mr-hardfork-plan-canonical.md|\
                doc/btx-peer-sync-hardening-tracker-2026-03-09.md|\
                doc/btx-realworld-validation-2026-03-07.md|\
                doc/btx-security-audit-report-2026-06-06-reassessment.md|\
                doc/btx-shielded-online-threat-review-2026-03-07.md|\
                doc/btx-shielded-pool-formal-audit-round6-2026-03-05.md|\
                doc/btx-shielded-v2-overhaul-tracker-2026-03-14.md|\
                doc/shielded-security-review-2026-03-05.md|\
                doc/tmp-metal-mining-optimizations-tracker-2026-03-28.md)
                    disposition="Reviewed historical evidence; no current MatMul policy claim"
                    reviewed=$((reviewed + 1))
                    ;;
                doc/JSON-RPC-interface.md|\
                doc/assumeutxo.md|\
                doc/btx-shielded-aggregation-rollup-tracker-2026-03-14.md|\
                doc/btx-smile-v2-future-proofed-settlement-tdd-2026-03-23.md|\
                doc/btx-windows-11-compile-handbook.md|\
                doc/dandelion-pp-implementation-spec.md|\
                doc/linux-release-builds.md|\
                doc/m15-full-lifecycle-runbook.md|\
                doc/pq-multisig-full-implementation-tracker.md|\
                doc/recovery-exit-cpu-plan-2026-06-14.md|\
                doc/release-process.md|\
                doc/security/README.md|\
                src/CMakeLists.txt|\
                src/test/CMakeLists.txt)
                    disposition="Reviewed incidental cross-subsystem/build reference; no transition policy"
                    reviewed=$((reviewed + 1))
                    ;;
                *)
                    disposition="REVIEW REQUIRED: MatMul-related without canonical-roadmap notice"
                    required=$((required + 1))
                    ;;
            esac
        fi
    fi
    safe_rel="${rel//|/\\|}"
    printf '| `%s` | %s |\n' "$safe_rel" "$disposition" >> "$rows"
done <<< "$files"

{
    echo '# MatMul v4.7 documentation inventory'
    echo
    echo 'Generated by `contrib/devtools/update-matmul-v47-doc-inventory.sh`.'
    echo 'The inventory covers repository documentation while excluding build outputs'
    echo 'and vendored LevelDB/secp256k1 documentation.'
    echo
    echo "Inventory totals:"
    echo
    echo "- documentation-like files: **$total**"
    echo "- MatMul/ExactReplay/proof-related files: **$matmul**"
    echo "- MatMul-related files reviewed or explicitly classified: **$reviewed**"
    echo "- MatMul-related files still requiring review: **$required**"
    echo
    echo 'Current and superseded policy documents are considered reviewed when they'
    echo 'carry a status/precedence notice pointing to the canonical roadmap.'
    echo 'Immutable release records, dated evidence with no current policy claim, and'
    echo 'incidental cross-subsystem/build references are classified explicitly rather'
    echo 'than rewritten. General documentation is left unchanged when it contains no'
    echo 'MatMul transition claim.'
    echo
    echo '| File | Review disposition |'
    echo '|---|---|'
    cat "$rows"
} > "$tmp"

mv "$tmp" "$out"
# mktemp creates the file 0600 and mv preserves that mode; make the generated
# doc world-readable like any other tracked file.
chmod 0644 "$out"
trap 'rm -f "$rows"' EXIT
echo "wrote $out ($total files; $required MatMul reviews outstanding)"
