from pathlib import Path
import csv,json
R=Path(__file__).resolve().parents[1]
# Each row is an independent required native assertion, not a reference test result.
families={
'NEUTRAL':('1, 3, 18','source/config audit and two generic providers',[
'No brand dispatch|Two generated provider IDs with identical manifests|Run identical enrollment and acquisition requests|Responses differ only in identity and observations, not privileges or routing',
'Fresh entrant|A provider absent from every shipped configuration|Enroll it with accepted role evidence|Normal role workflow succeeds without code changes or privileged allowlisting',
'No default financial host|A clean installation and no provider binding|Open reserve and funding views|No financial provider is auto-enrolled and no credentials are requested by a model package',
'Functional profiles only|Shipped role/configuration catalogues|Inspect all canonical profiles|Profiles are keyed by roles and supported effects rather than institutions',
'Reference tenant neutrality|Generic fixtures with permuted names|Run full fixture journeys|No tenant receives an implicit special role',
'Attribution survives|Research citations and third-party license notices|Run scoped neutrality check|Legitimate source/license attribution remains; operational brand branches fail',
'No package authority|A valid model package naming a preferred custodian|Inspect and acquire the package|The package cannot establish custody or provider root trust',
'White-label parity|Two themed portals using one SDK|Execute the same authorized draft flow|Theme changes no schema, role or authorization behavior',
'No global registry requirement|No central provider directory reachable|Use explicit enrolled origins|All chosen roles remain usable without directory approval',
'Renaming invariance|Provider display name changes but identity remains pinned|Refresh its manifest|Display changes confer no new trust or automatic binding',
]),
'NEGOTIATE':('4, 16','real native codec, versioned registry and signatures',[
'Extension parent binding|Accepted HCP and v1.1 profile bodies|Read v1.2 discovery|Both parent references and schema/operation digests match the registered contract',
'Old routes preserved|A snapshot of all 84 preceding operations|Compare and execute representative old requests|Paths, bodies, effects and hashes preserve the existing contract',
'Unknown critical type|A signed envelope with an unknown V1_2-like name|Submit to the native verifier|Unknown type is rejected before storage or privileged effects',
'Domain separation|One valid role manifest signature|Relabel it as an asset record|Verification fails despite an identical body',
'Canonical vectors|Duplicate keys, exponents, floats and negative zero|Parse in gateway, SDK and native reader|All reject the same invalid signed meaning',
'Expired extension|A formerly valid expired extension profile|Start new v1.2 work|New work is denied while historical records remain inspectable',
'Old server behavior|A v1.1-only server|Request v1.2 planning|Explicit unsupported result; no approximation through unrestricted old funding',
'No Core version change|Existing Core v3 packages and locks|Run v1.2 handoff|Exact package bytes and identities remain unchanged',
'Sequence rollback|A newer role manifest already accepted|Replay a prior signed manifest|Rollback cannot restore removed service authority',
'Key rotation|Enrolled root, old and new operation keys|Rotate with an accepted monotonic transition|New key works only for its role and historical receipts retain their provenance',
]),
'ROLE':('3, 11','registered service routes and real dependency probes',[
'Analytics-only service|A provider with no custody connection|Advertise portfolio analytics|Read projections work; custody and funding actions remain unavailable',
'Discovery-only service|A signed catalogue provider|Acquire a free public package|No financial dependency is created',
'Role effect match|A funding operation advertised as READ|Validate its manifest|ROLE_EFFECT_MISMATCH blocks publication',
'Missing production route|A manifest names an unregistered operation|Publish roles|Manifest is rejected rather than advertising a stub',
'Unsupported network|A provider supports a different native network|Bind it for current-network finance|Network mismatch prevents activation',
'Disabled adapter|An installed adapter marked DISABLED|Probe role availability|Disabled is visible and is not returned as an empty successful balance',
'Conformance specificity|Unit tests pass but native signing has no evidence|Publish role evidence|Only the supported evidence level is reported; custody proof is not inferred',
'Specialist composition|Separate discovery, custody and analytics providers|Run an entity-scoped workflow|Each service receives only its relevant request and authority',
'Effect dependency|An operation needs two roles and one is absent|Attempt it through the registry|Missing role returns a specific unavailable result',
'No brand priority|Two equally eligible generic providers|Resolve by explicit customer policy|Documented policy and observations decide selection, not a hidden preferred brand',
]),
'BIND':('3, 14','authenticated multi-tenant service binding integration',[
'Owner acceptance|A proposed binding with no owner consent|Attempt activation|Binding remains inactive',
'Wrong entity|A valid token for entity A and binding for B|Read or mutate binding B|Entity scope denies access without leaking its secrets',
'Least effects|An active READ binding|Attempt a planning or record operation|Effect outside the binding is denied',
'Audience isolation|Discovery and custody use distinct audiences|Forward the discovery token to custody|Audience validation rejects it',
'Revocation|An active binding with queued new work|Revoke and dispatch queued work|No new effect starts under the revoked generation',
'Recovery after revoke|A pre-existing uncertain funding intent|Revoke general binding|Restricted original-provider reconciliation remains possible without new-spend authority',
'Provider substitution|Discovery A fails; B is separately approved|Switch discovery|Public acquisition resumes; uncertain finance is not replayed at B',
'Expiry during read|A binding expires while an immutable export read is active|Complete read and start a new one|Lease-safe active read finishes under policy; new effect is denied',
'Concurrent updates|Two admins change the same binding generation|Commit both|One succeeds and one gets a version conflict',
'No secret export|Bindings use OS secret references|Export customer configuration|No access token, private key or reusable secret is included',
]),
'ASSET':('5, 7','asset master and rights adapters with native record verification',[
'Namespaced identity|Two assets share a label but have distinct authority IDs|Register both|They remain distinct and are not merged by display text',
'Identifier collision|Two contradictory claims to one accepted namespace/value|Ingest second claim|Open collision break and block ambiguous merge',
'Native network binding|Same-looking reserve units on two network identities|Import assets|Network-qualified IDs remain distinct',
'No synthetic security|A public model and no financial rights|Register it|It remains a capability resource; no ticker, fund unit or security ID is created',
'Rights issuer|A license claim signed by an unaccepted issuer|Apply rights|Claim remains unaccepted and cannot grant title',
'Transfer restriction|A nontransferable license|Create a portability export|Facts export, but no transfer permission is invented',
'Public sponsorship|A contribution to a public release|Record outcome|Sponsor commitment does not become exclusive IP or revenue entitlement',
'Entity relationship|A public parent-company record|Attempt a subsidiary debit|No financial authority follows from the relationship',
'Expired rights|A time-bounded accepted license|Project after expiry|Current rights view changes without rewriting historic records',
'Native funds unchanged|A new institutional asset registration|Compare native wallet/ledger before and after|No balance, UTXO or ownership mutation occurs',
]),
'POSITION':('6','durable batch ingestion and bitemporal source selection',[
'Exact replay|An accepted source/generation/sequence body|Ingest it twice|One logical observation and unchanged watermark',
'Conflicting sequence|Same source key and different signed bodies|Ingest the conflict|Quarantine and explicit OBSERVATION_CONFLICT',
'Effective-time cutoff|An accepted future-effective position|Project before its effective time|Earlier valid position remains current',
'Recorded-time cutoff|A late correction to a prior effective date|Reproduce the earlier report cutoff|Original result is preserved; later report includes correction',
'Closed position|A later valid CLOSED observation|Build current and historical views|Current excludes it; earlier historical view retains it',
'Sequence gap|Source skips a required sequence|Apply a later batch|Coverage becomes incomplete until reconciliation',
'Atomic batch|One invalid row in a batch of valid rows|Commit ingestion|No partial published batch or advanced watermark',
'Source precedence|Custody and treasury feeds describe one position|Project under accepted custody source policy|Quantity is counted once with corroboration retained',
'Omnibus attribution|Several customer lots share one address|Import the source mapping|Distinct beneficial positions are not collapsed by address',
'Generation reset|A source restarts with a new generation|Receive a reset sequence|Require accepted new snapshot/reconciliation rather than compare unrelated counters',
]),
'VALUE':('7','valuation adapter and exact decimal calculations',[
'Known zero|An eligible position with a current actual zero value|Aggregate|Return zero, not unavailable',
'Missing value|An eligible position with no valuation|Aggregate|Mark unpriced and return unavailable or labeled partial subtotal',
'Stale mark|An expired valuation formerly current|Build a new projection|It cannot feed a current complete financial metric',
'Purpose separation|A model replacement scenario has a monetary estimate|Build financial NAV|Scenario estimate is excluded',
'Position value once|A valuation already represents the whole position|Aggregate|Do not multiply quantity a second time',
'FX mapping|A position and report use different currencies|Aggregate without an accepted FX observation|Reject or mark unavailable rather than assume a rate',
'Exact rounding|Decimal rates and mixed currency exponents|Convert at the declared rounding boundary|Result matches pinned integer/decimal vectors',
'Nonfinite inputs|NaN, infinity, negative implied price or invalid exponent|Validate valuation|Reject before report publication',
'Late price correction|A corrected effective mark arrives later|Reproduce both observation cutoffs|Both historical versions remain deterministic',
'No execution price leak|A fresh reporting price differs from signed funding quote|Execute existing allocation|Original execution authority and quote rules prevail',
]),
'METRIC':('7, 8','metric policy and whole-portfolio aggregate tests',[
'AUM mandate|Managed and unmanaged financial positions|Calculate AUM|Only currently mandated eligible positions enter',
'AUC custody|Custodied and view-only positions|Calculate AUC|Only actual custody scope enters',
'AUA administration|An administration-only platform|Calculate assets|Report AUA under its definition, not management authority',
'Nonfinancial exclusion|Public model records with large utility estimates|Calculate financial totals|No fabricated cash value or NAV inclusion',
'Replica count|One recipe deployed on twenty devices|Count capability holdings|One holding plus twenty deployment observations, not twenty assets',
'Overlap metrics|One position is both managed and custodied|Display institutional dashboard|Separate overlapping metrics, no summed grand total',
'Cost basis|A licensed resource with actual acquisition cost|Produce cost and market views|Cost appears only under its accepted basis',
'Empty complete book|A verified complete empty source snapshot|Aggregate|Return complete zero with zero eligible count',
'Unavailable source|A required source fails before confirming holdings|Aggregate|Do not show complete zero or claim full coverage',
'New assets bridge|Internal reallocations and external inflows enter one product|Calculate growth|Firm net-new assets exclude internal transfers and performance',
]),
'EXPOSURE':('7, 13','bounded financial and operational graphs',[
'Direct vs lookthrough|A parent fund and all its holdings|Generate both views|Each view is valid; parent and children are never added together',
'Cycle detection|Financial lookthrough graph A to B to A|Expand|Bounded cycle error with no infinite work',
'Depth ceiling|A graph exceeds depth sixteen|Expand|Reject or truncate as explicit incomplete coverage under policy',
'Weight overflow|Nonlevered children sum above one|Validate|Reject without accepted leverage policy',
'Unknown residual|Only eighty percent of underlying exposure is known|Expand|Retain twenty percent unresolved residual',
'Operational edge|Capability depends on a runtime|Calculate financial exposure|No monetary weight is inferred',
'Negative or nonfinite weight|Malformed financial edge|Validate|Reject before aggregate arithmetic',
'Per-source duplicates|Same lookthrough relationship arrives twice|Reconcile|One logical edge under accepted identity',
'Graph budget|An adversarial wide recursive graph|Expand within request budget|CPU/memory stay bounded; incomplete result is explicit',
'Rights dependency|A capability loses a license dependency|Run operational scenario|Flag affected use rights without changing unrelated reserve price',
]),
'PROJECTION':('8, 15','database snapshot, paging and report services',[
'Snapshot vector|Several sources at different sequences|Create projection|Record all accepted watermarks and explicit coverage',
'Concurrent ingestion|Source updates during paging|Fetch every page|No duplicates or skipped positions within the pinned snapshot',
'Cross-tenant cursor|A cursor issued to tenant A|Use it as tenant B|Deny without disclosing A data',
'Changed filter cursor|An existing cursor and changed metric/filter|Continue|Cursor mismatch is rejected',
'Historical reproducibility|A signed projection before corrections|Rebuild using stored cutoffs and policies|Identical included records and values',
'Source outage|One expected feed is stale|Create projection|Partial status and a linked break remain visible',
'Large book|One hundred thousand actual synthetic rows|Project and export|Measured bounded memory and correct row count',
'No financial mutation|Projection and scenario requests|Compare available balances and intents|No reservations, signatures or new finance intents',
'Private inventory|A local client declines detailed reporting|Project|No complete local inventory or memory address appears',
'Policy revision|Metric definition changes|Create a new report|New policy ID is bound; old report retains old definition',
]),
'IMPORT':('10, 15','authenticated binary staging, persistence and signed manifests',[
'Exact chunk|Authenticated chunk with declared correct length/hash|Stage and import|Digest and byte length match the manifest',
'Corrupt chunk|One byte changes after manifest signing|Validate import|Reject before publication',
'Tenant-owned handle|Tenant B references A staged chunk|Validate|CHUNK_NOT_OWNED with no data leak',
'Duplicate chunks|Manifest repeats a chunk ID|Validate|Reject ambiguous row accounting',
'Row count mismatch|Manifest total differs from parsed rows|Validate|Reject and leave published view unchanged',
'Mapping change|Validation used one mapping digest|Commit under another|CAS rejects commit',
'Atomic publication|Crash before and after import commit marker|Restart|Either old view or complete new view, never partial published rows',
'Idempotent commit|Retry the same validated manifest|Commit twice|One published generation and same receipt',
'Formula-safe CSV|Text cells start with spreadsheet formula characters|Export CSV and canonical JSONL|Presentation is safe and original signed JSONL remains exact',
'No money import|Manifest contains a plausible account balance|Publish projection|No custody credit or spendable balance is created',
]),
'INSTRUCTION':('9, 12','portfolio bridge into actual v1.1 drafting routes',[
'Draft only|An accepted portfolio instruction|Translate|Existing v1.1 draft exists; no financial authorization or reservation',
'Entity mismatch|An instruction for another legal entity|Prepare|Deny before draft creation',
'Stale projection|Instruction references expired or unacceptable source state|Prepare|Specific stale-source error and no effects',
'Changed instruction|Same business ID with changed exposure|Translate again|Idempotency conflict rather than a second draft',
'Equivalent retry|Same instruction and business ID|Retry translation|Same draft and receipt',
'Existing approval|A translated draft receives valid v1.1 approvals|Execute via old route|Normal reserve/committee/native checks remain required',
'No scope escalation|Analytics credentials can read and draft|Attempt executeAllocation|Execution scope and policy deny',
'Desktop context|External app broadcasts capability context|Receive it|View or explicit draft only; no financial/local execution',
'No remote inference|External service option is selected for comparison|Translate|No public prompt-routing action is created',
'Provider finance ownership|Original provider has an uncertain child transaction|Switch analytics provider|No replay of that financial child at the new provider',
]),
'SECURITY':('4, 14','native signature/authentication and hostile integration tests',[
'Real signature|Production generated role keys|Verify all new envelope families|Valid signatures accepted; tampering rejected by native ML-DSA path',
'Wrong key role|A model publisher signs a custody observation|Accept as authoritative custody|Rejected without separately enrolled custody authority',
'Sender constraints|Stolen token without accepted proof key|Call privileged record/binding route|Denied by actual OAuth sender-binding implementation',
'Duplicate JSON fields|Two scope fields with different entities|Submit raw request|All parsers reject, no differential authorization',
'SSRF origin|A source hint targets internal metadata or changes DNS result|Fetch under integration|Egress/rebinding policy rejects unauthorized target',
'No token passthrough|One provider token is present in the hosted connector|Run cross-provider workflow|Only independently scoped credentials reach each audience',
'Injection text|Asset description contains SQL, shell and agent directives|Register and display|Data remains escaped; no query, process or wallet authority',
'Body ceiling|Oversized signed body or nested graph|Parse|Reject within allocation and recursion ceilings',
'Replay binding|An expired nonce or revoked provider record|Start new effect|Denied without losing historical read evidence',
'Secret sentinel|Seed test credentials in each protected zone|Run exports, logs, model handoff and context|No sentinel appears outside its approved secret store',
]),
'UX':('17, 12','real browser and accessibility harness',[
'Neutral enrollment|An unknown generic provider and a new user|Complete connection wizard|Same usable steps as any incumbent; requested roles are clear',
'Entity clarity|Group view with two entities|Start capital draft|Payer must be selected and remains visible',
'Metric definition|Dashboard shows AUM and AUC|Open definitions|Scope, basis, overlap and as-of are visible',
'Partial view|One missing valuation and one source gap|Render portfolio|No false zero or complete badge; evidence link works',
'Keyboard-only flow|No pointer input|Connect, inspect and draft|Logical focus order, visible focus and accessible controls',
'Screen-reader status|An async projection completes or fails|Observe live regions|Meaningful state announced without exposing secrets',
'Financial vs local|Funding confirms while device is offline|Render Activity|Capital and readiness remain separate',
'Export preview|Private scope selected|Create export|Preview shows data scope/redaction and requests proper authority',
'Desktop view safety|Context arrives from another app|Open matching record|No automatic execute or unrestricted localhost call',
'Provider exit|Customer revokes analytics/discovery|Open local capability and pending finance|Local public use persists; original obligations remain visible',
]),
'RECOVERY':('10, 15, 18','multi-process restart, failover and migration lab',[
'Staging crash|Chunk upload stops before final hash|Restart|No accepted chunk handle; bounded orphan cleanup',
'Job cancellation|Running projection/export/import before commit|Cancel then retry read|No false completed financial effect; leases released safely',
'Cancel after commit|Import published just before cancel|Cancel|Return already committed outcome, not a fake rollback',
'Database failover|Accepted observation and outbox pending|Fail over database/process|One published event and replay-safe consumer behavior',
'Stale source recovery|Required source returns after outage|Reconcile snapshot|Coverage improves with new evidence and old reports remain reproducible',
'Provider root compromise|Revoke an enrolled operational key|Receive new records and inspect history|New effects denied; history retains revocation context',
'Open funding on rollback|Disable v1.2 with an older funding intent pending|Run recovery|Existing reconciliation and refund routes remain available',
'Mapping rollback|Return from new mapping to previous compatible mapping|Re-export stored snapshot|Original records are preserved and versions explicit',
'Large export pressure|Slow consumer and constrained disk/memory|Run concurrent finance reads|Export backpressure does not exhaust financial service capacity',
'Cross-provider uncertainty|Read provider switches during funding uncertainty|Recover|Original provider remains owner of financial reconciliation',
]),
'COMPAT':('2, 4, 18, 19','combined build, regression suite and independent reviews',[
'Base signatures|Golden HCP/1 and v1.1 signed vectors|Read with new codec|Exact original bytes and identities retain meaning',
'Base operation map|Captured preceding schema registry|Generate combined OpenAPI|All 84 old operation definitions compare equal',
'No duplicate engine|Integrated source and production call graph|Audit service construction|New work extends existing engine/ledger/downloader boundaries',
'Consensus isolation|Monetary-only build and tests|Build without hosted extension|Consensus behavior and existing wallet state remain unaffected',
'Old client|v1.1 client against upgraded server|Run old discovery/funding/handoff|No regression in supported prior contracts',
'Feature disabled|Server disables institutional roles|Request new and old functions|New roles report unavailable; old accepted recovery continues',
'Real local handoff|Translated draft becomes approved acquisition|Use a real supported local runtime|Correct local result and no CEX heartbeat dependency',
'Native funding lifecycle|Translated research plan in isolated chain lab|Fund, observe and refund under actual terms|Native and custody evidence, not only simulator success',
'Two-provider institutional roundtrip|Two generic providers and portfolio-system fixture|Export/import/propose/approve/handoff|No source-code branding and no forged asset totals',
'Independent closeout|Fresh reviewers with all evidence tiers|Audit and rerun real findings|Every mandatory case has actual status and no inherited reference PASS',
]),
}
journeys=[
('J01','New entrant without bespoke code','Deploy two providers with generated identities. Publish roles, enroll one customer, discover a public capability and prepare it locally.','No brand branch, funded wallet or central provider registry is needed. Retain manifests, server logs and real local-runtime output.'),
('J02','Split-service customer','Bind discovery A, custody B and analytics C for one entity. Read a reserve, prepare a capability plan and export its result.','Audience-specific tokens, exact role checks and no cross-provider financial replay. Capture sanitized network boundaries.'),
('J03','Institutional custody statement','Ingest a source statement, its duplicate in another feed and a declared authoritative mapping.','AUC counts one beneficial position; backing assets and liabilities do not create duplicate customer wealth.'),
('J04','Managed reserve mandate','Add an actual test mandate to selected financial positions while leaving other holdings unmanaged.','AUM changes only for mandated holdings; AUC and technology coverage stay separate.'),
('J05','Business treasury capital loop','Use an existing v1.1 workload comparison to create a reserve allocation. Bring it through the new portfolio instruction interface.','Translation drafts, existing committee approves, existing HCP executes, local BTX prepares; no second engine.'),
('J06','Family group segregation','Load company, trust and personal books under read-only group access. Adviser prepares a draft for one entity.','Principal/entity approval required; no pooling or implicit cross-entity transfers.'),
('J07','Whole-portfolio fund view','Represent a real-form synthetic fund interest with partially known underlying reserve exposure.','Direct NAV counts parent once; look-through substitutes children with explicit residual coverage.'),
('J08','Late source correction','Create month-end report, then ingest a later correction effective at month end.','Earlier observation cutoff reproduces old report; new cutoff produces a linked corrected version.'),
('J09','Unknown value under outage','Remove one price and one required source while other data remains current.','Report partial/unavailable facts instead of zero; no execution authority follows from estimate.'),
('J10','Native research commitment','Translate a portfolio research instruction into v1.1 allocation, authorize and use real isolated native funding.','Ledger/chain/commitment reconcile; a later refund follows original terms and original provider.'),
('J11','Public release to cognitive holding','Fund an actual isolated release fixture, obtain disclosed bytes and prepare a supported local runtime.','Financial receipt, right/use record, exact recipe and readiness remain separate.'),
('J12','Signed export and hostile import','Export a snapshot to JSONL/CSV, tamper with one chunk, then import the intact set into a second provider.','Tampered input rejected, valid import atomically published, original signatures and tenant scope preserved.'),
('J13','Desktop analyst journey','Select an asset context in a generic institutional desktop fixture and open its reserve/capability view.','Context can read or prepare an explicit draft; no token, trade or runtime execution is embedded.'),
('J14','Portfolio technology business','Import several client books for analytics without any management mandate.','Coverage and client-specific metrics are reportable; technology vendor AUM is not invented.'),
('J15','Reserve and operational shocks','Apply a reserve-price shock and an independent provider-outage shock to a frozen projection.','Financial change and operational impacts have distinct units and methodology; local acquired capability survives gateway loss.'),
('J16','Concurrency and idempotency','Many agents retry the same instruction while admins revise role/policy state.','One exact draft per business operation; changed requests conflict; stale authority does not execute.'),
('J17','Scale and cancellation','Run the declared 100k-row process workload and separately the 10m-row institutional lab, with slow readers and cancellation.','Correct row counts, bounded memory/disk and measured throughput; unsupported large lab remains explicit.'),
('J18','Provider exit with pending capital','Revoke discovery/analytics and move portable records while a native financial child is uncertain.','Local use and new read discovery work; original provider reconciles financial child, no duplicated spend.'),
('J19','Migration and rollback','Migrate actual v1.1 fixtures, accept v1.2 import/position records, then disable new v1.2 effects.','Old contracts/financial recovery and read evidence survive; no Core v4, native ledger or consensus change.'),
('J20','Neutral commercial demonstration','Demonstrate the same reserve/portfolio/capability workflow for a full venue, a specialist analytics provider and a greenfield entrant.','Same schemas and conformance; fee bases and new external assets are factual and distinct, not inferred from downloads.'),
]
rows=[]
s='# Native Acceptance and Whole-System Journeys\n## Cognitive Reserve Layer v1.2\n\n**BTX 0.34.8 · 17 September 2026**\n\nThis catalogue adds 160 native cases and 20 journeys to the existing HCP/1 and v1.1 programme. Every native case begins NOT_RUN. Reference tests are separate and do not prove custody, cryptography, process or runtime execution.\n\n# Evidence contract\n\nFor each case retain candidate fingerprint, binary hashes, test command, test-network/configuration identity, actor/scope, relevant before/after state, exact assertions and sanitized logs under `evidence/CR12/<case-id>/`. Run through registered production paths. Record unit, process, chain, browser and external-system evidence separately. A case is not PASS merely because a symbol or HTTP route exists.\n\n'
for family,(sections,env,items) in families.items():
 assert len(items)==10
 s+=f'# CR12-{family}\n\nSpecification sections: {sections}. Required environment: {env}.\n\n'
 for n,item in enumerate(items,1):
  title,given,when,then=item.split('|');cid=f'CR12-{family}-{n:02d}'
  rows.append(dict(case_id=cid,title=title,spec_sections=sections,environment=env,given=given,when=when,then=then,status='NOT_RUN',evidence_path=f'evidence/CR12/{cid}/'))
  s+=f'## {cid} — {title}\n\n**Given:** {given}. **When:** {when}. **Then:** {then}.\n\n**Required evidence:** Registered native/process assertions appropriate to the family, including failure effects and source identity. **Initial status:** NOT_RUN.\n\n'
s+='# Whole-system journeys\n\n'
for jid,title,steps,proof in journeys:
 s+=f'## CR12-{jid} — {title}\n\n{steps}\n\n**Acceptance:** {proof}\n\n**Evidence:** `evidence/CR12/{jid}/`; record all invoked native operations, financial/local state transitions and real dependency results. **Initial status:** NOT_RUN.\n\n'
s+='# Release closure\n\nPreserve all previous regression cases and compare old contracts. Fresh reviewers inspect financial/operational accounting, source authority, privacy, role composition, data-import boundaries and actual call-path evidence. Record unresolved environment limits explicitly. No production change, fund movement, push or release flag update is authorized by this test catalogue.\n'
(R/'docs/06_Acceptance_and_Journeys.md').write_text(s)
(R/'tests/ACCEPTANCE_TESTS.md').write_text(s)
with (R/'tests/native-acceptance-v1.2.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
(R/'tests/journeys.json').write_text(json.dumps([dict(id=j,title=t,steps=a,acceptance=b,status='NOT_RUN') for j,t,a,b in journeys],indent=2))
(R/'tests/traceability.json').write_text(json.dumps({'case_count':len(rows),'families':{k:{'sections':v[0],'environment':v[1],'cases':10} for k,v in families.items()},'journeys':20},indent=2))
print(len(rows),'cases;',len(journeys),'journeys')
